axon:
  events:
    database: dfms-events-store
    snapshot-limit: 3
  amqp:
    exchange: dfms.out.exchange
    durable-messages: true
    transaction-mode: none
external:
  amqp:
    bind:
      route-key: '*'
    queue: dfms.event.queue
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: dfms-cmd
  data:
    mongodb:
      database: ${axon.events.database}
ùserver:
  port: 8090